// <auto-generated />
using System;
using DogTrials.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogTrials.Api.Migrations
{
    [DbContext(typeof(DogTrialsDbContext))]
    [Migration("20260122141812_AddTrialCounters")]
    partial class AddTrialCounters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogTrials.Api.Entities.Trial", b =>
                {
                    b.Property<Guid>("TrialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EventSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FormVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("HostClub")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("OrganizerSlug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SecretaryEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("SportCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TrackingSlug")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComputedColumnSql("[OrganizerSlug] + '-' + [EventSlug]", true);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("TrialId");

                    b.HasIndex("OrganizerSlug", "EventSlug")
                        .IsUnique()
                        .HasDatabaseName("UX_Trials_OrganizerSlug_EventSlug");

                    b.ToTable("Trials", (string)null);
                });

            modelBuilder.Entity("DogTrials.Api.Entities.TrialCounter", b =>
                {
                    b.Property<Guid>("TrialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NextSequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("TrialId");

                    b.ToTable("TrialCounters", null, t =>
                        {
                            t.HasCheckConstraint("CK_TrialCounters_NextSequenceNumber_Positive", "[NextSequenceNumber] >= 1");
                        });
                });

            modelBuilder.Entity("DogTrials.Api.Entities.TrialCounter", b =>
                {
                    b.HasOne("DogTrials.Api.Entities.Trial", "Trial")
                        .WithOne("Counter")
                        .HasForeignKey("DogTrials.Api.Entities.TrialCounter", "TrialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("DogTrials.Api.Entities.Trial", b =>
                {
                    b.Navigation("Counter");
                });
#pragma warning restore 612, 618
        }
    }
}
